### ISSUE TITLE
#2710

### ISSUE THREAD

**Issue by Arseneme** [ZuxingGit/pygments#14]
**Before:**
![屏幕截图 2024-06-09 103112](https://github.com/pygments/pygments/assets/161684706/1d83fb1e-521f-4d51-8650-7a90b337e935)
**After:**
![后](https://github.com/pygments/pygments/assets/161684706/2315f738-a182-461c-99ad-718aae9795fb)

**Details changes：**
path: `pygments/lexers/dotnet.py`
![屏幕截图 2024-06-09 104354](https://github.com/pygments/pygments/assets/161684706/9f32186d-ede3-4bbf-9424-cbe93e8cacf0)

**Comment by Arseneme** [comment]
https://github.com/pygments/pygments/issues/2710

**Comment by adluu2k1** [comment]
Plan Two is the only possible solution, in my opinion, since our goal is to improve a lexer, not to create a new custom lexer and, therefore, Plan One is not suitable.

**Comment by Arseneme** [comment]
> Plan Two is the only possible solution, in my opinion, since our goal is to improve a lexer, not to create a new custom lexer and, therefore, Plan One is not suitable.

Okay, I will delete the first plan later. Thank you for your suggestion.

**Comment by ZuxingGit** [comment]
PR accepted: https://github.com/pygments/pygments/pull/2726#issuecomment-2156674192
